dmBitLyUrl:
  columns:
    short:          { type: string(32), notnull: true, unique: true }
    expanded:       { type: string(1000), notnull: true }
  indexes:
    expanded_index:
      fields:
        expanded:
          length:   1000